export const wordLibrary = [
  "Garaż",
  "Świetlica",
  "Jurów",
  "Plaża",
  "Hubinek",
  "Somalia",
  "Akademik",
  "Polska",
  "Kraków",
  "Podlasie",
  "Indie",
  "Afryka",
  "Jaskinia",
  "Dżungla",
  "Piwnica",
  "Siłownia",
  "Zakopane",
  "Tajlandia",
  "Czechy",
  "SVZ",
  "Tabasco",
  "Most",
  "Londyn",
  "Morze Bałtyckie",
  "Półwysep",
  "Gdańsk",
  "Berlin",
  "Klub ze striptizem",
  "Stare Miasto",
  "Starówka",
  "Togo",
  "Stodoła",
  "Chlew",
  "Obora",
  "Pole",
  "Dwór",
  "Autostrada",
  "Ameryka Południowa",
  "Kopiec Kraka",
  "Kopiec Wandy",
  "Prądnik Czerwony",
  "Tarnów",
  "Bełżec",
  "Tomaszów Lubelski",
  "Siódemka (szkoła w TL)",
  "Indie",
  "Naleśnikarnia",
  "Radecznica",
  "Altanka",
  "Bar",
  "Pijalnia wódki i piwa",
  "Sklep monopolowy",
  "Gibraltar",
];
